version: "3.7"

# docker-compose run --rm --service-port app bash
# docker-compose up -d
services:
  app:
    # build: .
    build:
      context: .
      dockerfile: ./nodejs/build/Dockerfile
      args:
        UID: "${LOCAL_UID:-2001}"
        GID: "${LOCAL_GID:-2001}"
        UNM: "${LOCAL_USER_NAME:-foobar}"
    volumes:
      - ./apps:/apps
    # environment:
    #   # ビルド後に参照できるようになる変数
    ports:
      # --service-ports
      - "10080:10080"
    stdin_open: true
    tty: true
    # extra_hosts:
    #   - "local_dev:$HOST_IP_ADDR"
