version: "3.7"

# docker-compose run --rm --service-port app bash
# docker-compose up -d
services:
  app:
    build:
      context: .
      dockerfile: ./nodejs/build/Dockerfile
    volumes:
      - ./apps:/apps
    # environment:
    #   # ビルド後に参照できるようになる変数
    ports:
      # --service-ports
      - "10080:10080"
    stdin_open: true
    tty: true
